apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-streamsets-operator-catalog
spec:
  displayName: IBM Streamsets
  image: cp.stg.icr.io/cp/ibm-streamsets-operator-catalog@sha256:5ed6d60682803af7ee73e58d255bddff6fe403773a069588a4ee6607d23d5b2e
  publisher: IBM Streamsets
  grpcPodConfig:
    securityContextConfig: legacy
  sourceType: grpc
  secrets:
  - ibm-entitlement-key
  updateStrategy:
    registryPoll:
      interval: 10m
