apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cpd-streamsets-operator-catalog
spec:
  displayName: IBM Streamsets
  image: icr.io/cpopen/ibm-streamsets-operator-catalog@sha256:564848135315667e7d356d15e4ac01f16c52f09d8ccf8c0f365c46a5a3f4f486
  publisher: IBM Streamsets
  grpcPodConfig:
    securityContextConfig: legacy
  sourceType: grpc
  secrets:
  - ibm-entitlement-key
  updateStrategy:
    registryPoll:
      interval: 10m
