apiVersion: streamsets.cpd.ibm.com/v1alpha1
kind: Misc-resources
metadata:
  name: misc-resources-sample
spec:
  # Default values copied from <project_dir>/helm-charts/misc-resources/values.yaml
  software-misc-resources:
    application:
      containerRegistry: cp.icr.io/cp/cpd/ibm-streamsets-
      dpmcliVersion: software-da90442114a1a46b25751d498687b0969cf5dd45
      imageSuffix: -amd64
    cloudProvider: CPD
    clusterDomain: svc.cluster.local
    dbHost: ibm-streamsets-self-managed-mysql-mysql-deploy-headless
    global:
      host: https://cpd-zen.apps.rosa.rosa.sl9v.p3.openshiftapps.com
    heapShipper:
      enabled: false
    nameSpaceServiceAccount: streamsets
  
  
