apiVersion: streamsets.cpd.ibm.com/v1alpha1
kind: Aster-security-ui
metadata:
  name: aster-security-ui-sample
spec:
  # Default values copied from <project_dir>/helm-charts/aster-security-ui/values.yaml
  aster-security-ui-deploy:
    appName: aster-security-ui-v1
    application:
      containerRegistry: cp.stg.icr.io/cp/cpd/ibm-streamsets-
      dpmcliVersion: software-da90442114a1a46b25751d498687b0969cf5dd45
      imageName: aster-security-ui
      imageSuffix: -amd64
      imageTag: software-2ac50dae7d107771d9953572935b00ae9e07327d
      port: 8080
    cloudProvider: CPD
    clusterDomain: svc.cluster.local
    configFile: |
      {
        "featureMap": {
          "saml": true,
          "scim": true,
          "socialDisabled": true,
          "getAccessLink": "https://streamsets.com/access/",
          "showSignUp": false,
          "cloudPak": true
        },
        "mixpanelConfig": {
          "mixpanelToken": ""
        },
        "firebaseConfig": {
          "apiKey": "AIzaSyA1sEvvjfTPDbjexJLeSm3UFDLM7Rm_v0k",
          "authDomain": "non-prod-stage-20730.firebaseapp.com",
          "databaseURL": "https://non-prod-stage-20730.firebaseio.com",
          "projectId": "non-prod-stage-20730",
          "storageBucket": "non-prod-stage-20730.appspot.com",
          "messagingSenderId": "901582138340",
          "appId": "1:901582138340:web:774c5621ce7b3691c035f1"
        }
      }
    dbHost: ibm-streamsets-self-managed-mysql-mysql-deploy-headless
    environment: default
    global:
      host: https://cpd-zen.apps.rosa.rosa.sl9v.p3.openshiftapps.com
    healthCheck:
      path: /admin/health
      port: 8080
    heapShipper:
      enabled: false
    hpa:
      maxReplicas: 3
      minReplicas: 2
    istio:
      enabled: true
    nameSpace: default
    nameSpaceServiceAccount: streamsets
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 64Mi
    virtualService:
      gateway: '{{ .Release.Namespace }}-sch-gateway'
      prefixes:
      - /streamsets/aster
      rewrite: /
  
  
