# permissions for end users to view aster-security-uis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-streamsets-operator
    app.kubernetes.io/managed-by: kustomize
  name: aster-security-ui-viewer-role
rules:
- apiGroups:
  - software.streamsets.ibm.com
  resources:
  - aster-security-uis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - software.streamsets.ibm.com
  resources:
  - aster-security-uis/status
  verbs:
  - get
