# permissions for end users to edit jobrunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-streamsets-operator
    app.kubernetes.io/managed-by: kustomize
  name: jobrunner-editor-role
rules:
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - jobrunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - jobrunners/status
  verbs:
  - get
