# permissions for end users to view messagings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-streamsets-operator
    app.kubernetes.io/managed-by: kustomize
  name: messaging-viewer-role
rules:
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - messagings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - messagings/status
  verbs:
  - get
