# permissions for end users to view misc-resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-streamsets-operator
    app.kubernetes.io/managed-by: kustomize
  name: misc-resources-viewer-role
rules:
- apiGroups:
  - software.streamsets.ibm.com
  resources:
  - misc-resources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - software.streamsets.ibm.com
  resources:
  - misc-resources/status
  verbs:
  - get
