# permissions for end users to edit mysqls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-streamsets-operator
    app.kubernetes.io/managed-by: kustomize
  name: mysql-editor-role
rules:
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - mysqls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - mysqls/status
  verbs:
  - get
