# permissions for end users to view static-resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-streamsets-operator
    app.kubernetes.io/managed-by: kustomize
  name: static-resources-viewer-role
rules:
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - static-resources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - static-resources/status
  verbs:
  - get
