# permissions for end users to edit static-resources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-streamsets-operator
    app.kubernetes.io/managed-by: kustomize
  name: static-resources-editor-role
rules:
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - static-resources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - streamsets.cpd.ibm.com
  resources:
  - static-resources/status
  verbs:
  - get
