# permissions for end users to view topologies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-streamsets-operator
    app.kubernetes.io/managed-by: kustomize
  name: topology-viewer-role
rules:
- apiGroups:
  - software.streamsets.ibm.com
  resources:
  - topologies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - software.streamsets.ibm.com
  resources:
  - topologies/status
  verbs:
  - get
