# permissions for end users to edit tunnelings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-streamsets-operator
    app.kubernetes.io/managed-by: kustomize
  name: tunneling-editor-role
rules:
- apiGroups:
  - software.streamsets.ibm.com
  resources:
  - tunnelings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - software.streamsets.ibm.com
  resources:
  - tunnelings/status
  verbs:
  - get
