actions:
  metadata:
    name: streamsetsOperator
    description: The actions required to install the Streamsets Operator cluster resources
  actionDefs:
    install:
      metadata:
        name: "install"
        description: "Install the Streamsets operator"
        case.launcher.type: "script"
        case.launcher.isdefault: true
      roles:
        - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
              The client must have oc installed, restricted scc available, and be running on Openshift Container Platform to execute the launcher script.
        and:
        - "/case/prereqs/k8sResources/restrictedSCC"
        - "/case/prereqs/k8sDistros/openshift"
        - "/case/prereqs/client/istioctl"
        - or:
          - "/case/prereqs/client/oc"
          - "/case/prereqs/client/kubectl"

      # User must have the ability to create cluster roles and custom resource definitions
      k8sPermissions:
        rules:
          - rule:
              group: rbac.authorization.k8s.io
              resource: clusterroles
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
              version: "*"
          - rule:
              group: apiextensions.k8s.io
              resource: customresourcedefinitions
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
              version: v1beta1
          - ifExpression: "/prereqs/k8sDistros/openshift"
            rule:
              group: security.openshift.io
              resource: securitycontextconstraints
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update

    uninstall:
      metadata:
        name: "uninstall"
        description: "Uninstall the Streamsets operator"
        case.launcher.type: "script"
      roles:
        - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
              The client must have oc installed to execute the launcher script.
        and:
        - or:
          - "/case/prereqs/client/oc"
          - "/case/prereqs/client/kubectl"
          - "/case/prereqs/client/istioctl"

      k8sPermissions:
        rules:
          - rule:
              group: rbac.authorization.k8s.io
              resource: clusterroles
              verbs:
                - "*"
          - rule:
              group: apiextensions.k8s.io
              resource: customresourcedefinitions
              verbs:
                - "*"

    installOperator:
      metadata:
        name: "installOperator"
        description: "Install the Streamsets operator"
        case.launcher.type: "script"
        case.cli.alias: "install-operator"
        case.launcher.isdefault: true
      roles:
        - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
              The client must have oc or kubectl installed, restricted scc available, and be running on Openshift Container Platform to execute the launcher script.
        and:
        - "/case/prereqs/k8sResources/restrictedSCC"
        - "/case/prereqs/k8sDistros/openshift"
        - "/case/prereqs/client/istioctl"
        - or:
          - "/case/prereqs/client/oc"
          - "/case/prereqs/client/kubectl"

      # User must have the ability to create cluster roles and custom resource definitions
      k8sPermissions:
        rules:
          - rule:
              group: rbac.authorization.k8s.io
              resource: clusterroles
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
              version: "*"
          - rule:
              group: apiextensions.k8s.io
              resource: customresourcedefinitions
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update
              version: v1beta1
          - ifExpression: "/prereqs/k8sDistros/openshift"
            rule:
              group: security.openshift.io
              resource: securitycontextconstraints
              verbs:
                - get
                - list
                - watch
                - create
                - patch
                - update  

    uninstallOperator:
      metadata:
        name: "uninstallOperator"
        description: "Uninstall the Streamsets operator"
        case.launcher.type: "script"
        case.cli.alias: "uninstall-operator"
      roles:
        - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
              The client must have oc or kubectl installed to execute the launcher script.
        and:
        - or:
          - "/case/prereqs/client/oc"
          - "/case/prereqs/client/kubectl"
          - "/case/prereqs/client/istioctl"
     
      k8sPermissions:
        rules:
          - rule:
              group: rbac.authorization.k8s.io
              resource: clusterroles
              verbs:
                - "*"
          - rule:
              group: apiextensions.k8s.io
              resource: customresourcedefinitions
              verbs:
                - "*"

    ## EVERYTHING PAST HERE IS FROM THE ORIGINAL SAMPLE CASE BUNDLE
    # actions related to catalog
    installCatalog:
      metadata:
        name: "installCatalog"
        description: "Install the Streamsets operator catalog"
        case.launcher.type: "script"
        case.cli.alias: "install-catalog"
      roles:
        - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
              The client must have oc installed, and be running on Openshift Container Platform to execute the launcher script.
        and:
        - "/prereqs/k8sDistros/openshift"
        - or:
          - "/case/prereqs/client/oc"
          - "/case/prereqs/client/kubectl"
      k8sPermissions:
        rules: []

    uninstallCatalog:
      metadata:
        name: "uninstallCatalog"
        description: "Uninstall the Streamsets operator catalog"
        case.launcher.type: "script"
        case.cli.alias: "uninstall-catalog"
      roles:
        - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
              The client must have oc or kubectl installed to execute the launcher script.
        and:
        - or:
          - "/case/prereqs/client/oc"
          - "/case/prereqs/client/kubectl"
      k8sPermissions:
        rules: []

    applyCustomResources:
      metadata:
        name: "applyCustomResources"
        description: "Applies the customs CRs"
        case.launcher.type: "script"
        case.cli.alias: "apply-custom-resources"
      roles:
        - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
              The client must have oc installed to execute the launcher script.
        and:
        - "/case/prereqs/client/oc"
      k8sPermissions:
        rules: []

    # actions related to airgap

    configureCredsAirgap:
      metadata:
        name: "configureCredsAirgap"
        description: "configures login credentails for an image registry"
        case.launcher.type: "script"
        case.cli.alias: "configure-creds-airgap"
      roles:
        - clusterAdmin
      k8sPermissions:
        rules: []

    configureClusterAirgap:
      metadata:
        name: "configureClusterAirgap"
        description: "configures global pullsecret and imagesourcecontentpolicy"
        case.launcher.type: "script"
        case.cli.alias: "configure-cluster-airgap"
      roles:
        - clusterAdmin
      requires:
        metadata:
          message:
            onFailure: |
              The configureClusterAirgap action must be run on OpenShift Container Platform on amd64 Linux.
              The minimum level of Kubernetes on each platform are described in the CASE prerequisites.
              The client must have oc installed to execute the launcher script.
        and:
          - "/case/prereqs/k8sDistros/kubernetes"
          - "/case/prereqs/k8sDistros/openshift"
          - "/case/prereqs/client/oc"
      k8sPermissions:
        rules: []

    mirrorImages:
      metadata:
        name: "mirrorImages"
        description: "Mirrors the images to a local registry using oc"
        case.launcher.type: "script"
        case.cli.alias: "mirror-images"
      roles:
        - clusterAdmin
      requires:
        and:
          - "/case/prereqs/client/oc"
          - "/case/prereqs/client/skopeo"
      k8sPermissions:
        rules: []

    # actions related to local docker registry

    initRegistry:
      metadata:
        name: "initRegistry"
        description: "Initialize a local docker registry"
        case.launcher.type: "script"
        case.cli.alias: "init-registry"
      roles:
        - clusterAdmin
      requires:
        and:
          - "/case/prereqs/client/openssl"
          - "/case/prereqs/client/htpasswd"
      k8sPermissions:
        rules: []

    startRegistry:
      metadata:
        name: "startRegistry"
        description: "Start a local docker registry container"
        case.launcher.type: "script"
        case.cli.alias: "start-registry"
      roles:
        - clusterAdmin
      requires:
        or:
          - "/case/prereqs/client/podman"
          - "/case/prereqs/client/docker"
      k8sPermissions:
        rules: []

    stopRegistry:
      metadata:
        name: "stopRegistry"
        description: "Stop a local docker registry container"
        case.launcher.type: "script"
        case.cli.alias: "stop-registry"
      roles:
        - clusterAdmin
      requires:
        or:
          - "/case/prereqs/client/podman"
          - "/case/prereqs/client/docker"
      k8sPermissions:
        rules: []
