resources:
  metadata:
    name: streamsetsOperator
  resourceDefs:
    containerImages:
    - image: cpopen/ibm-streamsets-operator
      tag: v5.1.0
      digest: sha256:5f5661db47d6388b5c7bdc99d2b1717853f2a94d61d4b804e4ea84418927ad0e
      mediaType: application/vnd.docker.distribution.manifest.list.v2
      registries:
      - host: icr.io
      manifests:
      - digest: sha256:4dad92e2d4612ce010388d9ce41556818aba225d8a03b443e3c5217344bcb15d
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: amd64
          os: linux
        tag: v5.1.0-amd64
      - digest: sha256:1a95702e67d7edc5c7a31680eb7e7fec694954b44be4f42261a207b228b8db2b
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: s390x
          os: linux
        tag: v5.1.0-s390x
      - digest: sha256:3afdf5d66b24818fb913ce1e997eb5476b3905682ec5b1714500538ab2b05ae5
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: ppc64le
          os: linux
        tag: v5.1.0-ppc64le
    - image: cpopen/ibm-streamsets-operator-bundle
      tag: v5.1.0
      digest: sha256:f73e0f867173e1f6072214dd6344b5e2993f66b95b3bf18a6b34c5df16ef5a9e
      mediaType: application/vnd.docker.distribution.manifest.list.v2
      registries:
      - host: icr.io
      manifests:
      - digest: sha256:6de2fb0f9249670121a075e4b66ecb52a0226ef3ba64e31bd0fa2606d9cc8e47
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: amd64
          os: linux
        tag: v5.1.0-amd64
      - digest: sha256:67f069792d254afffb6e14f60a64a9a0c3624d11762d19fdf95f7e6d45caf0b1
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: s390x
          os: linux
        tag: v5.1.0-s390x
      - digest: sha256:746e0bfbfbdabda556bfbb7a8c2eab61b6ed9f791ab21d926416fa7158a51ac0
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: ppc64le
          os: linux
        tag: v5.1.0-ppc64le
      metadata:
        operators_operatorframework_io:
          bundle:
            mediaType: registry+v1
    - image: cpopen/ibm-streamsets-operator-catalog
      tag: v5.1.0
      digest: sha256:515564cb7f059cb166301a43c0c71be5994ad2331f020e3cec17dc4f78de1ba9
      mediaType: application/vnd.docker.distribution.manifest.list.v2
      registries:
      - host: icr.io
      manifests:
      - digest: sha256:564848135315667e7d356d15e4ac01f16c52f09d8ccf8c0f365c46a5a3f4f486
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: amd64
          os: linux
        tag: v5.1.0-amd64
      - digest: sha256:81c6cb601a2b30f7906d4b29e205c75612d8bc360a6c539095f476581fcc9416
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: s390x
          os: linux
        tag: v5.1.0-s390x
      - digest: sha256:0a97f4349d843877bc956409998ededc7771e13a19bc9cddf0bb73a920c56d95
        mediaType: application/vnd.docker.distribution.manifest.v2
        platform:
          architecture: ppc64le
          os: linux
        tag: v5.1.0-ppc64le
      metadata:
        operators_operatorframework_io:
          catalog:
            cpcicd_ibm_com:
              targetCatalogs:
                catalogRefs:
                - ibm-public: {}
            mediaType: registry+v1;impl=fbc 
    files:
    - mediaType: application/vnd.case.resource.script.bash.v1+launcher
      ref: launch.sh
    - mediaType: application/vnd.case.resource.script.bash.v1
      ref: airgap.sh
    - mediaType: application/vnd.case.resource.script.bash.v1
      ref: launch-impl.sh
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-olm/catalog-source.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-olm/operator-group.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-olm/subscription.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/istio/istio.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/clusterrole.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/clusterrole_binding.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/auth_proxy_service.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/aster-security-ui_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/aster-security-ui_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/aster-security_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/aster-security_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/auth_proxy_client_clusterrole.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/auth_proxy_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/auth_proxy_role_binding.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/banner_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/banner_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/connection_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/connection_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/docs_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/docs_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/jobrunner_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/jobrunner_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/leader_election_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/leader_election_role_binding.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/messaging_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/messaging_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/metering_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/metering_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/misc-resources_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/misc-resources_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/mysql_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/mysql_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/notification_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/notification_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/pipelinestore_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/pipelinestore_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/provisioning_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/provisioning_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/scheduler_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/scheduler_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/security_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/security_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/sequencing_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/sequencing_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/sla_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/sla_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/timeseries_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/timeseries_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/topology_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/topology_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/tunneling_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/tunneling_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/static-resources_editor_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/rbac/static-resources_viewer_role.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_sch-istios.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_aster-securities.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_aster-security-uis.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_banners.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_connections.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_docs.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_jobrunners.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_messagings.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_meterings.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_misc-resources.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_mysqls.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_notifications.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_pipelinestores.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_provisionings.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_schedulers.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_securities.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_sequencings.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_slas.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_timeseries.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_topologies.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_static-resources.yaml
    - mediaType: application/vnd.case.resource.k8s.v1+yaml
      ref: op-cli/config/crd/bases/streamsets.cpd.ibm.com_tunnelings.yaml
